---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Parsing TCR data downloaded from Adaptive Biotech

Download the data as follows:
- navigate to <https://clients.adaptivebiotech.com/pub/dewolf-2022-gvhd>
- click explore this project
- log in (making an account if needed)
- click "Open in Analyses"
- click "Analyses on the nav pane
- select all
- click export -> export Sample (NOT  V2!)
- wait patiently
- continue waiting; resist the urge to try the process again
- eventually move downloaded zip to this repo, unpack, and move the tsv files to `data/raw_TCR_data/`.


```{R}
tcr_data_dir <- "data/raw_TCR_data/"
```

The resulting file `TCR/tcr_unified.csv` is used for later analyses including the GLIPH2 analysis.

```{r tcr-raw-data-parsing}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)

dir.create("data/TCR", showWarnings = FALSE)

tcr_raw_output <- file.path("data/TCR", "tcr_unified.csv")

if (!file.exists(tcr_raw_output)){
  raw_files <- sort(dir(tcr_data_dir, pattern = "*.tsv", full.names = TRUE))
  if (length(raw_files) == 0){
    stop(paste0("No files found within ", tcr_data_dir))
  }
  tcr_raw_original <- map(raw_files, .f=function(x){
    # x = "sampleExport.2022-06-01_05-18-41//Balb-c_1_blood.tsv"
    read.csv(x, sep = "\t") %>% mutate(sample_name=gsub("\\.tsv", "", basename(x))) 
    #data.frame(sample_name=gsub("\\.tsv", "", basename(x)), sample_amount_ng=1)
  }) %>% bind_rows() %>% 
    mutate(
      #sample_name = gsub("T_cells", "Tcells", sample_name), 
      org = case_when(
        grepl("^Pt", sample_name) ~ "Human",
        grepl("^Balb-c", sample_name) ~ "Mouse",
        grepl("^Recipient_", sample_name) ~ "Mouse",
        grepl("^Donor", sample_name) ~ "Mouse",
        TRUE ~ "FixMe"),
      samp_type = case_when(
        grepl("^Donor", sample_name) ~ "Donor",
        grepl("^Pt", sample_name) ~ "Patient",
        grepl("^Balb-c", sample_name) ~ "Healthy",
        grepl("^Recipient_", sample_name) ~ "Recipient",
        TRUE ~ "FixMe"),
      indv_type = case_when(
        grepl("[Dd]onor", sample_name) ~ "Donor",
        grepl("^Pt", sample_name) ~ "Recipient",
        grepl("^Balb-c", sample_name) ~ "Recipient",
        grepl("^Recipient_", sample_name) ~ "Recipient",
        TRUE ~ "FixMe"),
      gvhd = case_when(
        grepl("[Dd]onor", sample_name) ~ "noGvHD",
        grepl("^Pt[A-G]", sample_name) ~ "GvHD",
        grepl("^Recipient_", sample_name) ~ "GvHD",
        grepl("^Balb", sample_name) ~ "noGvHD",
        grepl("^Pt[H-J]", sample_name) ~ "noGvHD",
      ),
      indv_id = case_when(
        grepl("^Balb-c", sample_name)     ~ gsub(".*?_(\\d*?)_.*", "\\1", sample_name ),
        grepl("^Pt", sample_name)   ~ gsub("Pt(.+?)_.*", "\\1", sample_name),
        grepl("^Donor", sample_name)     ~ gsub(".*?_(\\d*?)_.*", "\\1", sample_name),
        grepl("Recipient_tx", sample_name) ~ gsub("Recipient_tx(\\d*?)_(\\d+)_.*", "\\2", sample_name),
        TRUE                     ~ "FixMe" 
      ),
      tissue = case_when(
        indv_type == "Donor" & org == "Mouse"     ~ "Tcells",
        indv_type == "Donor" & org == "Human"     ~ "graft_blood",
        grepl("^Balb-c", sample_name)   ~ gsub(".*_\\d_(.*)$", "\\1", sample_name),
        grepl("^Pt", sample_name)   ~ gsub("Pt._(.*)$", "\\1", gsub("_TCRB", "",   sample_name)),
        grepl("Recipient_tx", sample_name) ~ gsub(".*_D\\d+_(.*)$", "\\1", sample_name),
        TRUE                     ~ "FixMe" 
      ),
      exp_rep =  ifelse(grepl("Recipient_tx", sample_name), gsub("Recipient_tx(\\d*?)_(\\d+)_.*", "\\1", sample_name), NA),
      collection_day = ifelse(grepl("Recipient_tx", sample_name), gsub("Recipient_tx.*D(\\d*?)_.*", "\\1", sample_name), NA)
    ) %>% 
    mutate(
      indv_label = paste(samp_type, indv_id),
      indv_label = ifelse(!is.na(exp_rep), paste0(indv_label, ", rep", exp_rep), indv_label ),
      indv_label = ifelse(!is.na(collection_day), paste0(indv_label, ", day ", collection_day), indv_label ),
      indv_tissue_label = paste(samp_type, indv_id, "-", gsub("_", " ", tissue)),
      sample_amount_ng = round(sample_amount_ng, 2)
    )  
  # Ran into strange issue with rounding the sample_ammount_ng; now we round above
  #   > read.csv("data/TCR/tcr_unified.csv") %>% filter(sample_name == "Balb-c_1_spleen") %>% pull(sample_amount_ng) %>% unique()
  #      [1] 1195.458 1195.458

  # View(tcr_raw_original %>% select(sample_name, org, gvhd,samp_type,  indv_id, tissue, exp_rep, collection_day) %>% distinct())
  
  # we sort here so the resulting file is hashable for ID
  write.csv(tcr_raw_original %>% arrange(sample_name, rearrangement), file = tcr_raw_output, row.names = FALSE)
}
```



## External Correlation Calculations

This can be done in R but the very large matrices make it slow. 
```

bsub -W 2:00 -n 128 -Is  bash
conda create -name tcr scipy pandas -y 
conda activate tcrs
bash scripts/get_file_pairs.sh ./samples/ > human_mouse_file_pairs.tsv
parallel -a human_mouse_file_pairs.tsv --bar --progress --colsep "\t" ~/miniconda3/envs/pd/bin/python scripts/AB-correlations.py {1} {2} > tmp

```
### Parsing and processing the TCR Data

The following chunk serves two purposes: reading in the TCR data, and calculating the JSD correlations based on the TCR profiles.  This takes a while, so the results are saved in an object called `tcr_objects.Rdata`. If this object is not found, it will create it. 


```{R, eval=FALSE}
tcr_objects_path <- "tcr_objects.Rdata"
if(!file.exists(tcr_objects_path)){
  tcr_raw_output <- file.path("data/TCR", "tcr_unified.csv") 
  if(tools::md5sum(tcr_raw_output) != "fd463374450fdbfca4565669dd49d89d") warning("tcr_unified.csv may need be re-created, it does not match the validated version")
  tcr_raw <- data.table::fread(tcr_raw_output) %>% 
    filter(frame_type == "In") %>%
    as_tibble()
  
  tcr_sample_metadata <- tcr_raw %>% 
    select(sample_name, org,  samp_type, collection_day,  sample_amount_ng, indv_type, exp_rep, gvhd, indv_id, indv_label, tissue, indv_tissue_label, species:total_templates_agg) %>% 
    distinct()


  clone_freq_by_pt = tcr_raw %>% 
    rename(patient_name=indv_label )

  NT_by_patient = clone_freq_by_pt %>% 
    select(patient_name, rearrangement, productive_frequency) %>%
    pivot_wider(names_from = patient_name, values_from = productive_frequency, values_fill = 0, values_fn = sum ) 
  
  AA_by_patient = clone_freq_by_pt %>% 
    select(patient_name, amino_acid, productive_frequency) %>%
    pivot_wider(names_from = patient_name, values_from = productive_frequency, values_fill =  0, values_fn = sum ) 
  
  paired_patients = expand.grid(pt_x = unique(clone_freq_by_pt$patient_name), pt_y = unique(clone_freq_by_pt$patient_name)) %>% 
    filter(pt_x != pt_y)
  
  list_of_paired_patient_nt = apply(paired_patients, 1, function(row){
    NT_by_patient %>%
      select(all_of(c(row[["pt_x"]],row[["pt_y"]])))
  }) 
  list_of_paired_patient_aa = apply(paired_patients, 1, function(row){
    AA_by_patient %>%
      select(all_of(c(row[["pt_x"]],row[["pt_y"]])))
  }) 
  
  
  
  num_overlap_clones2 <- function(df){
    # count rows where both columns are greater than zero
    nrow(df[df[,1] > 0 & df[,2] > 0, ])
  }
  
  num_shared_clone = list_of_paired_patient_nt %>% 
    map(~num_overlap_clones2(.)) %>% 
    unlist(.)
  
  num_shared_aa = list_of_paired_patient_aa %>% 
    map(~num_overlap_clones(.)) %>% 
    unlist(.)
  
  paired_patients$num_shared_clones = num_shared_clone
  paired_patients$num_shared_aa = num_shared_aa
  
  shared_clones <- paired_patients
  
  ##to draw the venn diagram, we need to create a different format
  ##the format is a list of vector, each vector containing the clone names present in each patient
  indvs <- unique(clone_freq_by_pt$patient_name)
  clones_per_pt <- lapply(setNames(indvs, indvs), function(x) {
    clone_freq_by_pt %>% filter(patient_name == x) %>% 
      filter(productive_frequency > 0) %>%
      pull(rearrangement) %>% unique()
  }) 
  aa_per_pt <- lapply(setNames(indvs, indvs), function(x) {
    clone_freq_by_pt %>% filter(patient_name == x) %>% 
      filter(productive_frequency > 0) %>%
      pull(amino_acid) %>% unique()
  })
  
  new_tcr_corrs <- read.csv(sep = "\t", "data/2022-08-29-tcr-correlations.tsv", header=FALSE, col.names = strsplit("fileA\tfileB\tsizeA\tsizeB\tnorm_sizeA\tnorm_sizeB\tJSD\tjsd_nt_norm\tjsd_aa_raw\tjsd_aa_norm\tmorisita_nt_raw\toverlapping_clones\toverlapping_aa", split = "\t")[[1]], na.strings = c("nan"))
  #do a double join to get all (non-unique combinations)
  tcr_corrs <- rbind(
    new_tcr_corrs,
    new_tcr_corrs %>% 
      mutate(fileX=fileA, fileA=fileB, fileB=fileX,
             sizeX=sizeA, sizeA=sizeB, sizeB=sizeX, 
             norm_sizeX=norm_sizeA, norm_sizeA=norm_sizeB, norm_sizeB=norm_sizeX) %>% 
      select(-fileX, -sizeX, -norm_sizeX)
  ) %>% 
    rename(sample1=fileA, sample2=fileB)  %>% 
    distinct()

  save(
    list = c(
      "tcr_sample_metadata", 
      "tcr_corrs",
      #"shared_clones",
      "clones_per_pt",
      "aa_per_pt",
      "tcr_raw"), 
    file = tcr_objects_path  )
  
} else{
  load(tcr_objects_path)
}

```










```{R, eval=FALSE}
tcr_objects_path <- "tcr_objects.Rdata"
if(!file.exists(tcr_objects_path)){
  tcr_raw_output <- file.path("data/TCR", "tcr_unified.csv") 
  if(tools::md5sum(tcr_raw_output) != "6f0f6e1bfc6ff1b040692d3a7dad20cc") warning("tcr_unified.csv may need be re-created, it does not match the validated version")
  tcr_raw <- data.table::fread(tcr_raw_output) %>% 
    filter(frame_type == "In") %>%
    as_tibble()
  tcr_sample_metadata <- tcr_raw %>% 
    select(sample_name, org,  samp_type, collection_day,  sample_amount_ng, indv_type, exp_rep, gvhd, indv_id, indv_label, tissue, indv_tissue_label) %>% 
    distinct()

    these_samples <-  unique(tcr_raw$sample_name)
  #tcr_raw <- tcr_raw %>% filter(sample_name %in%  these_samples[1:50])
  tcr_raw_filt <-  tcr_raw %>% 
    select(sample_name, rearrangement, amino_acid, productive_frequency) 
  
  dt_tcr_w <- tcr_raw_filt %>% 
    data.table::as.data.table() %>% 
    data.table::dcast(sample_name~rearrangement, fill = 0, value.var="productive_frequency" ) %>%
    column_to_rownames("sample_name") %>% 
    data.matrix()
  
  dt_tcr_w_bysample <- tcr_raw_filt %>% 
    data.table::as.data.table() %>% 
    data.table::dcast(rearrangement~sample_name, fill = 0, value.var="productive_frequency" ) %>%
    column_to_rownames("rearrangement") %>% 
    data.matrix()

  
  tmp <- rep(1, n_distinct(tcr_raw_filt$sample_name))
  names(tmp) <- rownames(dt_tcr_w)
  all.equal(tmp, rowSums(dt_tcr_w))
  
  dt_tcr_w_aa <- tcr_raw_filt %>% 
    data.table::as.data.table() %>% 
    data.table::dcast(sample_name~amino_acid, fill = 0, value.var="productive_frequency", fun.aggregate = sum ) %>%
    column_to_rownames("sample_name") %>% 
    data.matrix()
  
  #df of all sample combinations
  sample_combinations <- expand.grid(
    sample1=rownames(dt_tcr_w),
    sample2=rownames(dt_tcr_w)
    ) %>%
    as_tibble() %>% 
    mutate(sample1=as.character(sample1), sample2=as.character(sample2))

  
  # calculate 
  system.time({tcr_raw_w_jsd  <- philentropy::JSD(dt_tcr_w, est.prob = "empirical")})
  ##    user   system  elapsed 
  ## 2962.610  227.388 3250.489 
  system.time({tcr_raw_w_jsd_aa  <- philentropy::JSD(dt_tcr_w_aa, est.prob = "empirical" )})
  
  # system.time({par_jsd <- for (i=0:(nrow(sample_combinations)/50), .combine=rbind) %dopar% {
  #    philentropy::JSD(dt_tcr_w[c(sample_combinations$sample1[(i*50):((i*50)+50)], sample_combinations$sample2[(i*50):((i*50)+50)]),], est.prob = "empirical")
  #   }
  # })
  # system.time({par_jsd <- foreach (i=0:(nrow(sample_combinations)/50), .combine=rbind) %dopar% {
  #    philentropy::JSD(dt_tcr_w[sample_combinations$sample1[(i*50):((i*50)+50)],], est.prob = "empirical")
  #   }
  # })

  # colnames(par_jsd) <- "jsd_new"
  # rownames(par_jsd) <- NULL  
  
  
  registerDoParallel(6)
  par_morisita <- foreach (i=1:nrow(sample_combinations), .combine=rbind) %dopar% {
    horn_morisita(dt_tcr_w[sample_combinations$sample1[i], ], dt_tcr_w[sample_combinations$sample2[i], ]) 
  }
  colnames(par_morisita) <- "morisita"
  rownames(par_morisita) <- NULL

  par_clone_overlap <- foreach (i=1:nrow(sample_combinations), .combine=rbind) %dopar% {
    tcr_raw_filt %>% filter(sample_name %in% c(sample_combinations$sample1[i], sample_combinations$sample2[i])) %>% pivot_wider(values_from = productive_frequency, names_from = sample_name) %>% drop_na() %>% nrow()
  }
  colnames(par_clone_overlap) <- "overlapping_clones"
  rownames(par_clone_overlap) <- NULL
  
  par_aa_overlap <- foreach (i=1:nrow(sample_combinations), .combine=rbind) %dopar% {
    tcr_raw_filt %>% filter(sample_name %in% c(sample_combinations$sample1[i], sample_combinations$sample2[i])) %>%
      select(-rearrangement) %>% 
      pivot_wider(values_from = productive_frequency, names_from = sample_name, values_fn = sum) %>% drop_na() %>% nrow()
  }
  colnames(par_aa_overlap) <- "overlapping_aa"
  rownames(par_aa_overlap) <- NULL

  stopImplicitCluster()
  
  
  sample_combinations <- cbind(sample_combinations, par_morisita,par_clone_overlap, par_aa_overlap )
  
  sample_n_clones <- tcr_raw_filt %>% 
    group_by(sample_name) %>%
    summarize(n_unique_tcrs=n())
    # the `colnames<-`(rownames(tcr_raw_w_jsd))  fixes the messed up column punctuation
  tcr_corrs <- pivot_longer(
    data.frame(tcr_raw_w_jsd) %>% 
      `colnames<-`(rownames(dt_tcr_w)) %>% 
      `rownames<-`(rownames(dt_tcr_w)) %>% 
      rownames_to_column("sample1"), 
    cols=-sample1 , names_to = "sample2", values_to = "JSD" ) %>% 
    full_join(
      pivot_longer(
        data.frame(tcr_raw_w_jsd_aa)  %>% 
          `colnames<-`(rownames(dt_tcr_w_aa)) %>% 
          `rownames<-`(rownames(dt_tcr_w_aa)) %>% 
          rownames_to_column("sample1"), cols=-sample1 , names_to = "sample2", values_to = "JSD_aa" ), by=c("sample1", "sample2")) %>% 
    full_join(sample_combinations,  by=c("sample1", "sample2")) %>% 
    left_join(sample_n_clones, by=c("sample1"="sample_name" )) %>% 
    left_join(sample_n_clones, by=c("sample2"="sample_name" )) 
    
  ggplot(tcr_corrs %>% filter(grepl("^PtA", sample1) , grepl("^PtA", sample2)) %>% 
           filter(n_unique_tcrs.x > 10, n_unique_tcrs.y>10), aes(x=n_unique_tcrs.x,y=n_unique_tcrs.y, color=JSD)) + geom_jitter(alpha=.2) + theme_classic()  +scale_x_log10( ) + scale_y_log10() 
  #+ scale_color_gradient2(mid = "white", low = "blue", high = "red" )
  
    ggplot(tcr_corrs %>% filter(grepl("^PtA", sample1) , grepl("^PtA", sample2)) %>% 
           filter(n_unique_tcrs.x > 10, n_unique_tcrs.y>10), aes(x=n_unique_tcrs.x,y=JSD)) + geom_jitter(alpha=.2) + theme_classic()  +scale_x_log10( ) + scale_y_log10() 
  ggplot(tcr_corrs %>% filter(grepl("^PtA", sample1) , grepl("^PtA", sample2)) %>% 
           mutate(mean_clones = mean(c(n_unique_tcrs.x, n_unique_tcrs.y))) %>%
           filter(n_unique_tcrs.x > 10, n_unique_tcrs.y>10), aes(x=JSD,y=mean_clones, color=JSD)) + geom_jitter(alpha=.2) + theme_classic()  +scale_x_log10( ) + scale_y_log10() + geom_smooth()

  
  # verify against original calculations if desired  
  if (FALSE){
    orig_jsd <- read.csv("JSD_MI_all.csv") %>% rename(JSDold=JSD) %>% select(sample1, sample2, JSDold)
    tcr_pairs_all <- tcr_raw_w_jsd  %>% rownames_to_column("raw_sample1") %>% 
      pivot_longer(cols=-raw_sample1, names_to="raw_sample2", values_to = "JSD") %>% 
      filter(grepl("Pt", raw_sample1) & grepl("Pt", raw_sample2))
    if (FALSE) write.csv(
      quote = FALSE,
      data.frame(new=unique(c(tcr_pairs_all$sample1, tcr_pairs_all$sample2)),
                 old=c(unique(c(orig_jsd$sample1, orig_jsd$sample2)), 
                       rep(NA, length(unique(tcr_pairs_all$sample1))- length(unique(orig_jsd$sample1))))), 
      file = "for_sample_name_key.csv")
    sample_key <- read.csv("sample_name_key.csv")
    tmp <- left_join(
      orig_jsd, 
      tcr_pairs_all%>% 
        left_join(sample_key, by=c("raw_sample1"="clean_names")) %>% 
        left_join(sample_key, by=c("raw_sample2"="clean_names")) %>% 
        rename(sample1=original_names.x, sample2=original_names.y) %>% 
        select(sample1, sample2, JSD), 
      by= c("sample1", "sample2")) %>%
      filter(!is.na(JSD)) %>%
      mutate(diff=JSD-JSDold)
    all.equal(tmp$JSDold, tmp$JSD)  
    #tmp %>%  arrange(desc(diff)) %>% write.csv("JSD_differences.csv", row.names = FALSE)
  }
  # Spearman calculations are not needed; see https://github.com/nickp60/DeWolf-GTEx-TCR/ if needed in future for some reason
  # tcr_corrs <- inner_join( jsd_tcr_pairs, combinations,  by=c("sample1"="x", "sample2"="y")) %>% 
  #  mutate(
  #     sample1_tissue=gsub(".*?_(.*)_.*", "\\1", sample1),
  #     sample2_tissue=gsub(".*?_(.*)_.*", "\\1", sample2),
  #     sample1_clean=gsub("(.*?)_(.*)_.*", "\\1", sample1),
  #     sample2_clean=gsub("(.*?)_(.*)_.*", "\\1", sample2)
  #   ) %>% rename(spearman=cor)
  # jsd_tcr_agg_individuals <- tcr_corrs %>% 
  #   select(sample1, sample2, JSD) %>% 
  #   pivot_wider(names_from="sample2", values_from="JSD") %>%
  #   column_to_rownames("sample1") %>%
  #   as.matrix()
  # spear_tcr_agg_individuals <- tcr_corrs %>% 
  #   select(sample1, sample2, spearman) %>% 
  #   pivot_wider(names_from="sample2", values_from="spearman") %>%
  #   column_to_rownames("sample1") %>%
  #   as.matrix()
  
  # jsd_tcr_agg_individuals<- jsd_tcr_agg_individuals[, rownames(jsd_tcr_agg_individuals)]
  # spear_tcr_agg_individuals<- spear_tcr_agg_individuals[, rownames(spear_tcr_agg_individuals)]
  # 

  # sample_patient_combos <-  sample_combinations %>% select(1:2) %>% 
  #   left_join(tcr_sample_metadata, by=c("sample1"="sample_name") ) %>%
  #   left_join(tcr_sample_metadata, by=c("sample2"="sample_name") ) %>%
  #   select(sample1, indv_label.x, sample2, indv_label.y) 
  #   #   right_join(tcr_raw_filt %>% select(sample_name, rearrangement), by=c("sample1"="sample_name"))
  # #   right_join(tcr_raw_filt %>% select(sample_name, rearrangement), by=c("sample2"="sample_name")) %>% 
  # #     group_by(indv_label.x)
  # registerDoParallel(6)
  # patient_combos %>% select(indv_label.x, indv_label.y) %>% distinct()
  # par_morisita <- foreach (i=1:nrow(patient_combos), .combine=rbind) %dopar% {
  #   
  #   horn_morisita(dt_tcr_w[sample_combinations$sample1[i], ], dt_tcr_w[sample_combinations$sample2[i], ]) 
  # }
  # colnames(par_morisita) <- "morisita"
  # rownames(par_morisita) <- NULL
  # 
  
    # from ./to_incorporate/venn_diagram_by_pt_withchart.R
  clone_freq_by_pt = tcr_raw %>% 
    rename(patient_name=indv_label )

  NT_by_patient = clone_freq_by_pt %>% 
    select(patient_name, rearrangement, productive_frequency) %>%
    pivot_wider(names_from = patient_name, values_from = productive_frequency, values_fill = 0, values_fn = sum ) 
  
  AA_by_patient = clone_freq_by_pt %>% 
    select(patient_name, amino_acid, productive_frequency) %>%
    pivot_wider(names_from = patient_name, values_from = productive_frequency, values_fill =  0, values_fn = sum ) 
  
  paired_patients = expand.grid(pt_x = unique(clone_freq_by_pt$patient_name), pt_y = unique(clone_freq_by_pt$patient_name)) %>% 
    filter(pt_x != pt_y)
  
  list_of_paired_patient_nt = apply(paired_patients, 1, function(row){
    NT_by_patient %>%
      select(all_of(c(row[["pt_x"]],row[["pt_y"]])))
  }) 
  list_of_paired_patient_aa = apply(paired_patients, 1, function(row){
    AA_by_patient %>%
      select(all_of(c(row[["pt_x"]],row[["pt_y"]])))
  }) 
  
  
  num_overlap_clones <- function(df){
    
    ##remove rows in which the clones are absent in both patients 
    remove_rows_zero = which(rowSums(df) == 0)
    df = df[-remove_rows_zero,]
    
    #remove rows in which the clones are absent in either patients
    remove_rows = c(which(df[,1] == 0), which(df[,2] == 0) )
    df = df[-remove_rows,]
    
    num_shared_clones = nrow(df) 
    
    return(num_shared_clones)
  }
  num_overlap_clones2 <- function(df){
    nrow(df[df[,1] > 0 & df[,2] > 0, ])
  }
  num_overlap_clones3 <- function(df){
    df[df == 0 ] <- NA
    df[complete.cases(df),]
#    nrow(df[df[,1] > 0 & df[,2] > 0, ])
  }
   num_overlap_clones4 <- function(df){
     df %>% 
       filter( .[[1]]  > 0 &  .[[2]]  >0 ) %>% 
       nrow
   } 
  
  system.time({num_shared_clone = list_of_paired_patient_nt %>% 
    map(~num_overlap_clones(.)) %>% 
    unlist(.)})
#     user  system elapsed 
#  28.673  10.437  39.418 
 system.time({num_shared_clone2 = list_of_paired_patient_nt %>% 
    map(~num_overlap_clones2(.)) %>% 
    unlist(.)})
#    user  system elapsed 
# 20.694  10.992  32.471 
 system.time({num_shared_clone3 = list_of_paired_patient_nt %>% 
    map(~num_overlap_clones3(.)) %>% 
    unlist(.)})
 #  user  system elapsed 
 # 46.596  24.906  73.296 
system.time({num_shared_clone4 = list_of_paired_patient_nt %>% 
    map(~num_overlap_clones4(.)) %>% 
    unlist(.)})
 #   user  system elapsed 
 # 21.314   3.113  24.700
num_shared_aa = list_of_paired_patient_aa %>% 
    map(~num_overlap_clones(.)) %>% 
    unlist(.)
  paired_patients$num_shared_clones = num_shared_clone
  paired_patients$num_shared_aa = num_shared_aa
  
  shared_clones <- paired_patients
  
  ##to draw the venn diagram, we need to create a different format
  ##the format is a list of vector, each vector containing the clone names present in each patient
  indvs <- unique(clone_freq_by_pt$patient_name)
  clones_per_pt <- lapply(setNames(indvs, indvs), function(x) {
    clone_freq_by_pt %>% filter(patient_name == x) %>% 
      filter(productive_frequency > 0) %>%
      pull(rearrangement) %>% unique()
  }) 
  aa_per_pt <- lapply(setNames(indvs, indvs), function(x) {
    clone_freq_by_pt %>% filter(patient_name == x) %>% 
      filter(productive_frequency > 0) %>%
      pull(amino_acid) %>% unique()
  })
  
  # tmp <- left_join(
  #   tcr_corrs %>% 
  #     mutate(sample1new = pmin(sample1, sample2), sample2new=pmax(sample1, sample2)) %>% 
  #     select(-sample1, -sample2) %>% distinct(), 
  #   new_tcr_corrs %>% 
  #     mutate(sample1new = pmin(fileA, fileB), sample2new=pmax(fileA, fileB)))  %>% 
  #   filter(sample1new != sample2new)
  # all.equal(tmp$JSD, tmp$jsd_nt_raw)
  
  # clones_per_pt <- list(
  #         PtA = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient A" & clone_freq_by_pt$sum_productive_frequency > 0], 
  #         PtB = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient B" & clone_freq_by_pt$sum_productive_frequency > 0], 
  #         PtC = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient C" & clone_freq_by_pt$sum_productive_frequency > 0],
  #         PtD = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient D" & clone_freq_by_pt$sum_productive_frequency > 0],
  #         PtE = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient E" & clone_freq_by_pt$sum_productive_frequency > 0],
  #         PtF = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient F" & clone_freq_by_pt$sum_productive_frequency > 0],
  #         PtG = clone_freq_by_pt$rearrangement[clone_freq_by_pt$patient_name == "Patient G" & clone_freq_by_pt$sum_productive_frequency > 0]
  # )
  # 
  
  save(list = c( "tcr_sample_metadata", "dt_tcr_w_bysample", "tcr_corrs", "shared_clones", "clones_per_pt", "aa_per_pt", "tcr_raw"), file = tcr_objects_path  )
  
} else{
  load(tcr_objects_path)
}

```





