---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup-38, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=10, fig.height=7) 
library(tidyverse) 
library(patchwork)  # for combining figures
library(dendextend) # for tanglegrams
library(ggrepel)
library(ggpubr)
library(rstatix)


theme_set(theme_classic())
if (interactive()) load("tcr_objects.Rdata")
uc_figs_dir <- file.path("figures", "UC")
dir.create(uc_figs_dir, showWarnings = FALSE)
figures_path <- file.path("figures", "UC")

```

# Comparing patients to UC cohort Validating Trees

Data were downloaded from https://clients.adaptivebiotech.com/pub/werner-2018-clinexpimmunol and moved to `data/UC_raw_TCR_data`

TCR JSDs were calculated similar to the description in 00-preprocess-TCR:
```
bash scripts/get_file_pairs.sh ./data/UC_raw_TCR_data/ > UC_file_pairs.tsv
parallel -a UC_file_pairs.tsv --bar --progress --colsep "\t" ~/miniconda3/envs/pd/bin/python scripts/AB-correlations.py {1} {2} > data/2022-10-12-UC-tcr-correlations.tsv
```

## recreating figure 5b
```{r}


uc_metadata = data.frame("raw"=gsub(".tsv", "", dir("data/UC_raw_TCR_data/", pattern = ".tsv"))) %>% 
  mutate(tissue=ifelse(grepl("Blood", raw), "blood", "rectum"),
         severity=factor(gsub(".*?_.*?_(.*)", "\\1", raw), levels = c("control", "mild_disease", "moderate_disease", "severe_disease"), ordered = TRUE),
         disease=ifelse(severity != "control", "disease", "control"),
         indv_label = gsub("(.*)?_.*?_(.*)", "\\1", raw)
  )

# # nonrectal_lower_GI <- c("colon", "ileum",  "mid_colon", "ascending_colon",  "colon_ascending","descending_colon", "jejunum", "transverse_colon", "L_colon",  "left_colon", "right_colon", "terminalileum"  )  
# nonrectal_lower_GI <- tissue_annotations[tissue_annotations$uc_group == "Large Intestine", "tissue"]
# upper_GI <- c("stomach", "esophagus", "duodenum", "small_intestine" )  
# upper_GI <- tissue_annotations[tissue_annotations$uc_group == "Small Intestine", "tissue"]
# 

# we change ascending_colon to colon_ascending to make it sort later alphabetically :/ 
tcr_corrs_anno <- tcr_corrs %>% 
  left_join(tcr_sample_metadata %>% select(sample_name:species), by=c("sample1" = "sample_name")) %>% 
  left_join(tcr_sample_metadata %>% select(sample_name:species), by=c("sample2" = "sample_name"))

thismetric = "JSD"
msk_uc_corrs <- read.csv(sep = "\t", "data/2022-10-12-UC-tcr-correlations.tsv", header=FALSE, col.names = strsplit("fileA\tfileB\tsizeA\tsizeB\tnorm_sizeA\tnorm_sizeB\tthreshold\tJSD\tjsd_nt_norm\tjsd_aa_raw\tjsd_aa_norm\tmorisita_nt_raw\toverlapping_clones\toverlapping_aa", split = "\t")[[1]], na.strings = c("nan")) %>%
    left_join(uc_metadata, by=c("fileA"="raw")) %>% 
    left_join(uc_metadata, by=c("fileB"="raw")) %>% 
  select(indv_label.x, indv_label.y, tissue.x, tissue.y, disease.x, all_of(thismetric)) %>%
  mutate(cohort = "UC") %>% 
  bind_rows(
    tcr_corrs_anno %>%   filter(org.x == "Human", org.y=="Human") %>% 
      mutate(disease.x = gvhd.x, cohort="MSK") %>% 
      select(indv_label.x, indv_label.y, disease.x, tissue.x, tissue.y,  all_of(thismetric), cohort)
  )%>%
  filter(tissue.x %in% c("blood", "autopsy_blood") ) %>% 
  # filter(tissue.x %in% c("blood", "autopsy_blood") | tissue.y %in% c("blood", "autopsy_blood")) %>% 
 filter(indv_label.x == indv_label.y, tissue.x != tissue.y)  %>% 
  inner_join(tissue_annotations %>% select(uc_group, tissue) %>% filter(uc_group != "") %>% distinct(), by=c("tissue.y" = "tissue")) %>% 
  mutate(xgroup=case_when(
    cohort == "UC" ~  paste0("UC - ", disease.x),
    cohort == "MSK" ~  paste0("GvHD - ", uc_group),
    TRUE ~ "Issue"
  ))

theselimits = sort(unique(msk_uc_corrs$xgroup))
theselimits <- theselimits[c(4,5,2,1,3)]

fig1R <- ggplot(msk_uc_corrs%>%
         rename(metic= all_of(thismetric)) %>%
         select(indv_label.x, xgroup, metic, tissue.x, tissue.y) %>% distinct() %>% 
         filter(!indv_label.x %in% c("P01", "P08")), aes(x=xgroup, y=metic)) + geom_boxplot(outlier.colour = NA, color="grey") +  
  geom_jitter(width = .1, height = 0) +
  scale_x_discrete(limits=theselimits) + theme_classic() +
  scale_y_continuous(limits = c(0, 1)) + 
  labs(
    title = paste("Blood-tissue pair", thismetric),
    x="",
    y=thismetric)

ggsave(plot=fig1R ,height=4,width=6, filename=file.path(figures_path, "Revision_fig1R.pdf"))

#plot with the data from Teichmann et al . as well (JSD calculated separately)

msk_uc_corrs2 = read.csv("JSD_public_comparisons.csv")

theselimits = sort(unique(msk_uc_corrs2$xgroup))
theselimits <- theselimits[c(1,5,6,3,4,2)]

JSD_public <- ggplot(msk_uc_corrs2%>%
         rename(metic= all_of(thismetric)) %>%
         select(indv_label.x, xgroup, metic, tissue.x, tissue.y) %>% distinct() %>% 
         filter(!indv_label.x %in% c("P01", "P08")), aes(x=xgroup, y=metic, fill = xgroup)) + geom_boxplot(alpha = .3) +  
  geom_jitter(width = .1, height = 0, color = "black", alpha = .5, size = 1) +
   scale_fill_brewer(palette="Set1") +
  scale_x_discrete(limits=theselimits) + theme_classic() + theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    title = paste("Blood-tissue pair", thismetric),
    x="",
    y=thismetric)

JSD_public


ggsave(plot=JSD_public ,height=4,width=5, filename=file.path(figures_path, "Revision_JSD_public.pdf"))

```



```{r}
# msk_uc_corrs <- read.csv(sep = "\t", "data/2022-10-12-UC-tcr-correlations.tsv", header=FALSE, col.names = strsplit("fileA\tfileB\tsizeA\tsizeB\tnorm_sizeA\tnorm_sizeB\tJSD\tjsd_nt_norm\tjsd_aa_raw\tjsd_aa_norm\tmorisita_nt_raw\toverlapping_clones\toverlapping_aa", split = "\t")[[1]], na.strings = c("nan")) %>%
#     left_join(uc_metadata, by=c("fileA"="raw")) %>% 
#     left_join(uc_metadata, by=c("fileB"="raw")) %>% 
#   select(indv_label.x, indv_label.y, tissue.x, tissue.y, disease.x, all_of(thismetric)) %>%
#   mutate(cohort = "UC") %>% 
#   bind_rows(
#     tcr_corrs_anno %>%   filter(org.x == "Human", org.y=="Human") %>% 
#       mutate(disease.x = gvhd.x, cohort="MSK") %>% 
#       select(indv_label.x, indv_label.y, disease.x, tissue.x, tissue.y,  all_of(thismetric), cohort)
#   )%>%
#   filter(tissue.x %in% c("blood", "autopsy_blood", "rectum", nonrectal_lower_GI, upper_GI),tissue.y %in% c("blood", "autopsy_blood", "rectum", nonrectal_lower_GI, upper_GI) ) %>% 
#   filter(tissue.x %in% c("blood", "autopsy_blood") | tissue.y %in% c("blood", "autopsy_blood")) %>% 
#  filter(indv_label.x == indv_label.y, tissue.x != tissue.y)  %>% 
#   mutate(
#     tissue.x = ifelse(tissue.x == "ascending_colon", "colon_ascending", tissue.x),
#     tissue.y = ifelse(tissue.y == "ascending_colon", "colon_ascending", tissue.y),
#     ) %>% 
#   mutate(tissueA = pmin(tissue.x, tissue.y),
#          tissueB = pmax(tissue.x, tissue.y)) %>% 
#   mutate(xgroup=case_when(
#     tissueB  == "rectum" & cohort == "MSK"  ~ "GvHD\n(rectum)",
#     tissueB %in% nonrectal_lower_GI ~ "GvHD\n(non-rectal lower GI)",
#     tissueB %in% upper_GI ~ "GvHD\n(Upper GI)",
#     TRUE ~ paste0("UC - ", disease.x )
#   ))
# 
# 



```

## Assessing shared clonotypes between patients among the two cohorts:

```{r}
raw_files <- sort(dir("data/UC_raw_TCR_data/", pattern = "*.tsv", full.names = TRUE))

UC_tcr_raw <- purrr::map(raw_files, .f=function(x){
    read.csv(x, sep = "\t") %>% mutate(sample_name=gsub("\\.tsv", "", basename(x))) 
  }) %>% bind_rows()  %>% left_join(uc_metadata, by=c("sample_name"="raw"))
  
# merge our and the UC paper's raw tcr data, and filter out bioidentities only found once
common_bio_identities <- bind_rows(
    tcr_raw %>% filter(frame_type == "In") %>% mutate(cohort= "GvHD") %>% 
      filter(sample_name %in% (tcr_sample_metadata %>% filter(org == "Human", gvhd == "GvHD", tissue != "graft_blood") %>% pull(sample_name))) %>% 
      select(sample_name, tissue, indv_label, cohort, productive_frequency, productive_templates, templates, bio_identity, rearrangement), 
    UC_tcr_raw%>% filter(frame_type == "In") %>%  mutate(cohort= "UC") %>% 
      filter(tissue !="blood", disease!="control") %>% 
      select(sample_name, tissue, indv_label, cohort, productive_frequency,  productive_templates, templates, bio_identity, rearrangement)
    ) %>% 
    arrange(bio_identity) %>% 
    group_by(bio_identity) %>% 
    filter(n() > 1) 

# filter to retain bioidentities found in both cohorts
by_pt_cross_cohort_common_bio_identities <- common_bio_identities %>% group_by(bio_identity) %>% filter( n_distinct(cohort) > 1)
# filter to retain bioidentities found in both cohorts, ignoring singletons
by_pt_cross_cohort_common_bio_identities_gt1 <- common_bio_identities %>% filter(templates > 1) %>% group_by(bio_identity) %>% filter(n_distinct(cohort) > 1)

 

# library(ggalluvial)


# only human
# no comparators
# relative abundance
# block by pt rather than tissue
# 

# dat <-by_pt_cross_cohort_common_bio_identities %>% 
#   mutate(tissue_clean = ifelse(grepl("blood", tissue, ignore.case = TRUE), "blood", tissue)) %>%
#   filter(tissue_clean %in% c("blood", "rectum")) %>%
#   group_by(cohort, tissue_clean,  bio_identity) %>% summarize(templates=sum(templates)) %>% 
#   ungroup() %>%
#   group_by(bio_identity, tissue_clean) %>%
#   filter(n_distinct(cohort) > 1 , n() > 1) %>%
#    as.data.frame()
# is_alluvia_form(dat, weight = templates)
# ggplot(dat,
#                 aes(x = cohort, stratum = tissue_clean, y=templates, fill=tissue_clean, alluvium = bio_identity)) +
#       geom_flow(stat = "alluvium", curve_type = "sigmoid", color = "gray45", size = .3) +
#       geom_stratum(alpha = 1) +
#   #    geom_text(aes(y=tissue_total *1.1, label=thislabel), size=15) +
#   # consider , color=NA) + 
#     scale_fill_discrete(guide="none") +
#     geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
#       theme_classic() +
#       theme(
#         axis.text.y = element_text(size = 15, color = "black"),
#         legend.position = "right",
#         axis.text.x = element_text(size = 15, angle = -30, color = "black", hjust = 0),
#         plot.margin = margin(r=80) #
#       ) +
#       scale_y_continuous(expand = c(0,0)) 
# 
# ggplot(by_pt_cross_cohort_common_bio_identities %>% 
#          filter(cohort=="GvHD") %>%
#          filter(grepl("^Pt", sample_name)) %>% 
#          group_by(sample_name) %>% 
#          summarize(shared_total_perc =100* sum(productive_frequency)), aes(y=sample_name, x= shared_total_perc)) + 
#   geom_bar(stat="identity")
# 
# # sanity check
# by_pt_cross_cohort_common_bio_identities %>% filter(sample_name == "PtC_pretx_blood_TCRB") %>% pull(templates) %>% sum()
# 
# 
# 
# by_msk_pr <- purrr::map(unique(by_pt_cross_cohort_common_bio_identities$indv_label), .f = function(pt){
#   if (pt %in% uc_metadata$indv_label){
#     return(data.frame())
#   }
#   thisdat <- by_pt_cross_cohort_common_bio_identities %>% group_by(bio_identity) %>% filter(pt %in%indv_label) %>% 
#     ungroup()
#   our_abund <-  thisdat %>% filter(indv_label == pt) %>% group_by(tissue) %>% summarize(cohort="MSK", indv_label=unique(tissue), total_abund = sum(productive_frequency))
# 
#   their_abund <- purrr::map(thisdat %>% filter(cohort=="GvHD", pt == indv_label) %>% pull("sample_name") %>% unique(),  .f = function(samp){
#     thistissdat <-   thisdat %>% group_by(bio_identity) %>% filter(samp %in% sample_name) %>% filter(cohort=="UC") %>% ungroup() %>% group_by(indv_label) %>%  summarize(cohort="UC", total_abund = sum(productive_frequency))  %>% mutate(tissue=tcr_sample_metadata[tcr_sample_metadata$sample_name == samp,] %>% pull("tissue"))  })  %>%  bind_rows()
#   bind_rows(our_abund, their_abund) %>% mutate( group = pt)
#   
# }) %>%  bind_rows()
# 
# ggplot(by_msk_pr, aes(x=total_abund, y=indv_label, fill=ifelse(indv_label==group, "grey", indv_label))) + 
#   geom_bar(stat="identity") + 
#     facet_grid(group~cohort, scales="free") + 
#   scale_fill_discrete()
# 
# 
# ggplot(by_msk_pr %>% filter(cohort == "MSK"), aes(x=total_abund, y=tissue)) + 
#   geom_bar(stat="identity") + 
#     facet_grid(group~., scales="free") + 
#   scale_fill_discrete() + 
# ggplot(by_msk_pr %>% filter(cohort == "UC"), aes(x=total_abund, y=tissue, fill=indv_label)) + 
#   geom_bar(stat="identity") + 
#     facet_grid(group~., scales="free") + 
#   scale_fill_discrete()


# final? 
# For each individual
by_msk_pt <- purrr::map(unique(by_pt_cross_cohort_common_bio_identities$indv_label), .f = function(pt){
  # ignore the UC individuals - we are counting per MSK patient
  if (pt %in% uc_metadata$indv_label){
    return(data.frame())
  }
  # select the bioidentities found in that patient
    thispatdat <- by_pt_cross_cohort_common_bio_identities %>% group_by(bio_identity) %>% filter(pt %in%indv_label) %>% 
    ungroup()
    # For each tissue
    purrr::map(thispatdat %>% filter(cohort=="GvHD", pt == indv_label) %>% pull("sample_name") %>% unique(),  .f = function(samp){
      # count the unique bioidentities found in the UC cohort
      thispatdat %>% group_by(bio_identity) %>% filter(samp %in%sample_name) %>% 
        ungroup() %>% filter(cohort == "UC") %>% summarize(samp=samp, n=n_distinct(bio_identity))
    }) %>%  bind_rows()
}) %>%  bind_rows()


ggplot(by_msk_pt %>% left_join(tcr_sample_metadata, by=c("samp"="sample_name")), aes(x=n, y=gsub("_TCRB", "", samp))) + 
  geom_bar(stat="identity") + 
    facet_grid(indv_label~., scales="free", space="free") + 
  scale_fill_discrete()   + 
  labs(x="Number of unique clones (bio-identity) found in UC study's tissues", y= "Sample")+
  scale_x_continuous(expand=c(0, 0))

```
