```{r setup-TCR, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=10, fig.height=7) 
library(tidyverse) 
library(patchwork)  # for combining figures
library(gplots)     # for heatmap.2
library(Hmisc)     # for pairwise Spearman Correlations
library(ggtree)    # for trees
library(philentropy) # for JSD
library(Hmisc)  # for rcorr
library(ape)   # for as.phylo
load("gtex_objects.RData")
```

# TCR Data
`unified_all.csv` contains the TCR data from the GVHD patients, and `unified_all.csv` contains the TCR data from the non-GVHD patients.
```{r}
all_tissues_tcr <- "tcr_objects.Rdata"
if(!file.exists(all_tissues_tcr)){
  if (!file.exists("unified_all.csv")) stop("unified_all.csv not found")
  if (!file.exists("unified_com.csv")) stop("unified_com.csv not found")
  tcr_raw <- rbind(
    read.csv("unified_all.csv", stringsAsFactors = F) ,
    read.csv("unified_com.csv", stringsAsFactors = F) 
  )
  # data.table makes this tractable
  these_samples <-  unique(tcr_raw$sample_name)
  
  tcr_raw_w <- tcr_raw %>% 
    select(sample_name, rearrangement, productive_frequency) %>%
    filter(!is.na(productive_frequency)) 
  
  dt_tcr_raw_w <- tcr_raw_w %>% 
    data.table::as.data.table() %>% 
    data.table::dcast(sample_name~rearrangement, fill = 0 ) 
  dt_tcr_raw_w_m <- as.matrix(dt_tcr_raw_w[, 2:ncol(dt_tcr_raw_w)])
  rownames(dt_tcr_raw_w_m) <- dt_tcr_raw_w$sample_name
  
  tcr_raw_w_jsd  <- JSD(dt_tcr_raw_w_m, est.prob = "empirical" )
  tcr_raw_w_jsd <- as.data.frame(tcr_raw_w_jsd)
  rownames(tcr_raw_w_jsd) <- colnames(tcr_raw_w_jsd) <-  rownames(dt_tcr_raw_w_m)
  
  jsd_tcr_pairs <-pivot_longer(tcr_raw_w_jsd %>% rownames_to_column("sample1"), cols=-sample1 , names_to = "sample2", values_to = "JSD" )
  # verify against original calculations origial 
  if (FALSE){
    orig_jsd <- read.csv("JSD_MI_all.csv") %>% rename(JSDold=JSD) %>% select(sample1, sample2, JSDold)
    tmp <- left_join(orig_jsd, tcr_pairs_all%>% select(sample1, sample2, JSD), by= c("sample1", "sample2"))
    all.equal(tmp$JSDold, tmp$JSD)
    print(head(tmp))
  }
  #memory error :(
  # tcr_raw_w_spearman  <- rcorr(dt_tcr_raw_w_m, type='spearman')[[1]]
  #memory error :(
  # tmp <- cor(dt_tcr_raw_w_m, use="complete.obs")
  combinations <- expand.grid(x=rownames(dt_tcr_raw_w_m), y=rownames(dt_tcr_raw_w_m)) %>% as.data.frame() %>% mutate(cor=NA)
  for (i in 1:nrow(combinations)){
    if (i %% 10 == 0) print(i)
    combinations$cor[i] = cor(method="spearman", dt_tcr_raw_w_m[combinations$x[i], ], dt_tcr_raw_w_m[combinations$y[i], ])
  } 
  tcr_corrs <- inner_join( jsd_tcr_pairs, combinations,  by=c("sample1"="x", "sample2"="y")) %>% 
   mutate(
      sample1_tissue=gsub(".*?_(.*)_.*", "\\1", sample1),
      sample2_tissue=gsub(".*?_(.*)_.*", "\\1", sample2),
      sample1_clean=gsub("(.*?)_(.*)_.*", "\\1", sample1),
      sample2_clean=gsub("(.*?)_(.*)_.*", "\\1", sample2)
    ) %>% rename(spearman=cor)
  jsd_tcr_agg_individuals <- tcr_corrs %>% 
    select(sample1, sample2, JSD) %>% 
    pivot_wider(names_from="sample2", values_from="JSD") %>%
    column_to_rownames("sample1") %>%
    as.matrix()
  spear_tcr_agg_individuals <- tcr_corrs %>% 
    select(sample1, sample2, spearman) %>% 
    pivot_wider(names_from="sample2", values_from="spearman") %>%
    column_to_rownames("sample1") %>%
    as.matrix()
  
  jsd_tcr_agg_individuals<- jsd_tcr_agg_individuals[, rownames(jsd_tcr_agg_individuals)]
  spear_tcr_agg_individuals<- spear_tcr_agg_individuals[, rownames(spear_tcr_agg_individuals)]
  save(list = c("tcr_corrs", "jsd_tcr_agg_individuals",  "spear_tcr_agg_individuals"), file = all_tissues_tcr  )
  
} else{
  load(all_tissues_tcr)
}



# tcr_agg_individuals[upper.tri(tcr_agg_individuals)] <- NA

```





```{r }
for (metri in c("JSD", "spearman")){
  tcr_agg_individuals <-  tcr_corrs %>% 
    select(sample1, sample2, metri) %>% 
    pivot_wider(names_from="sample2", values_from=metri) %>%
    column_to_rownames("sample1") %>%
    as.matrix()
  if (metri == "spearman"){
    dend_<- hclust(1-as.dist(tcr_agg_individuals), method = "single") %>% as.dendrogram()
    samples_ordered <- hclust(1-as.dist(tcr_agg_individuals), method = "single")$labels[c( hclust(1-as.dist(tcr_agg_individuals), method = "single")$order)]
  } else{
    dend_<- hclust(as.dist(tcr_agg_individuals), method = "single") %>% as.dendrogram()
    samples_ordered <- hclust(as.dist(tcr_agg_individuals), method = "single")$labels[c( hclust(as.dist(tcr_agg_individuals), method = "single")$order)]
  }
  samples_ordered_clean <- gsub("(.*?)_(.*)_TCRB", "\\1 - \\2", samples_ordered)

  labels_colors(dend_) <- data.frame(Tissue = labels(dend_)) %>%
    left_join(., tissue_key) %>% pull(col)
  
  
  
  tmp <- ape::as.phylo(dend_)
  tmp$edge.length <- tmp$edge.length*2
  tmpheight <- sort(stats::cophenetic(dend_), decreasing = TRUE)[1] 
  
  ugly_specific_tissue_key <- tcr_corrs %>% select(sample1, sample1_tissue, sample1_clean) %>% distinct() 
  # %>% column_to_rownames("sample1")
  # ugly_specific_tissue_key <- ugly_specific_tissue_key[rownames(tcr_agg_individuals), ] %>% 
  #   rownames_to_column("sample1")#%>%   left_join(specific_tissue_key, by=c("sample1_tissue" = "TissueTCR"))
  
  tick_pos <- seq(0, 1, .1)
  ticks=data.frame(xorig=tick_pos, x=tick_pos - (1-tmpheight),
                   lab=rev(tick_pos),  yend=rep(.3, length(tick_pos))) 
  thesecolors <- c(RColorBrewer::brewer.pal(9, name="Set1"),"black", "grey")[c(1:5, 7, 8, 9, 10, 11 )]
  names(thesecolors)  <- unique(ugly_specific_tissue_key$sample1_clean)
  # see  https://stackoverflow.com/questions/58492013/possible-to-force-non-occurring-elements-to-show-in-ggplot-legend
  # for why we use "limits" not "breaks" in the manual color scale
  (p_tcr_all <- ggtree(tmp)  %<+% ugly_specific_tissue_key + xlim(-.05, 1.25) +
      geom_tiplab(aes(color=sample1_clean, label=sample1_tissue), 
                  offset = 0.01,#(1-max(tmp$edge.length)) + .01, 
                  align = FALSE, linetype = NA) +
      geom_tippoint() +
      
      #geom_text2(aes(label = node)) +    
      scale_linetype(guide="none") +
      labs(color="Patient") +
      scale_color_manual(values=thesecolors, guide="none") +
      geom_segment(y=0, yend=0, x=min(ticks$x), xend=max(ticks$x)) + 
      annotate(geom="text",        x=ticks$x, y=-1, label=ticks$lab )   + 
      geom_segment(data=ticks, aes(y=-yend, yend=0, x=x, xend=x )) +
      theme(legend.position = c(.2, .95)) 
      #guides(col = guide_legend(ncol = 4, override.aes = list(size=5))) + 
  )
  if(metri=="spearman"){
    p_tcr_all <-  p_tcr_all +
      geom_cladelab(node=91 , label=names(thesecolors)[1], angle=270, align=F, geom='text', textcolor=thesecolors[1], offset=.2, vjust=-.1, barcolor = thesecolors[1]) +
      geom_cladelab(node=89, label=names(thesecolors)[2], angle=270, align=F, geom='text', textcolor=thesecolors[2], offset=.2, vjust=-.1, barcolor = thesecolors[2]) +
      geom_cladelab(node=95, label=names(thesecolors)[3], angle=270, align=F, geom='text', textcolor=thesecolors[3], offset=.2, vjust=-.1, barcolor = thesecolors[3]) +
      geom_cladelab(node=97, label=names(thesecolors)[4], angle=270, align=F, geom='text', textcolor=thesecolors[4], offset=.2, vjust=-.1, barcolor = thesecolors[4]) +
      geom_cladelab(node=98, label=names(thesecolors)[5], angle=270, align=F, geom='text', textcolor=thesecolors[5], offset=.2, vjust=-.1, barcolor = thesecolors[5]) +
      geom_cladelab(node=93, label=names(thesecolors)[6], angle=270, align=F, geom='text', textcolor=thesecolors[6], offset=.2, vjust=-.1, barcolor = thesecolors[6]) +
      geom_cladelab(node=87, label=names(thesecolors)[7], angle=270, align=F, geom='text', textcolor=thesecolors[7], offset=.2, vjust=-.1, barcolor = thesecolors[7]) 
  } else {
    p_tcr_all <-  p_tcr_all +
      geom_cladelab(node=94, label=names(thesecolors)[1], angle=270, align=F, geom='text', textcolor=thesecolors[1], offset=.2, vjust=-.1, barcolor = thesecolors[1]) +
      geom_cladelab(node=98, label=names(thesecolors)[2], angle=270, align=F, geom='text', textcolor=thesecolors[2], offset=.2, vjust=-.1, barcolor = thesecolors[2]) +
      geom_cladelab(node=91, label=names(thesecolors)[3], angle=270, align=F, geom='text', textcolor=thesecolors[3], offset=.2, vjust=-.1, barcolor = thesecolors[3]) +
      geom_cladelab(node=96, label=names(thesecolors)[4], angle=270, align=F, geom='text', textcolor=thesecolors[4], offset=.2, vjust=-.1, barcolor = thesecolors[4]) +
      geom_cladelab(node=97, label=names(thesecolors)[5], angle=270, align=F, geom='text', textcolor=thesecolors[5], offset=.2, vjust=-.1, barcolor = thesecolors[5]) +
      geom_cladelab(node=86, label=names(thesecolors)[6], angle=270, align=F, geom='text', textcolor=thesecolors[6], offset=.2, vjust=-.1, barcolor = thesecolors[6]) +
      geom_cladelab(node=89, label=names(thesecolors)[7], angle=270, align=F, geom='text', textcolor=thesecolors[7], offset=.2, vjust=-.1, barcolor = thesecolors[7]) 
  }
  ggsave(p_tcr_all, height = 11, width = 9, filename = file.path(figs_dir, str_glue("{metri}_TCR_patients_all.pdf")))
  
  
  (pmat_tcr_all<- ggplot(
    tcr_corrs %>% 
      rename(thisfill=metri) %>% 
      mutate(
      sample1=factor(sample1, levels = samples_ordered, ordered = TRUE),
      sample2=factor(sample2, levels = samples_ordered, ordered = TRUE),
      lab = round(thisfill, 2),
    ), aes(x=sample1, y=sample2, fill=thisfill)) + 
      geom_tile() + 
      coord_fixed(ratio=1) + 
      geom_text(aes(label=lab), color="grey50", size=1)+
      #scale_fill_viridis_c(option = "A", breaks=seq(0, 1, .2), limits=c(0, 1)) +
      scale_fill_viridis_c(option = "A") +
      guides(fill = guide_colourbar(direction = "horizontal")) + 
      scale_y_discrete(position = "right", expand = c(0,0), labels=samples_ordered_clean) +
      scale_x_discrete( expand = c(0,0), labels=samples_ordered_clean) +
      labs(subtitle=metri) +
      theme(axis.text.x = element_text(angle=315, hjust=0, size=9), legend.position = "bottom")
  )
  ggsave(pmat_tcr_all, width = 14, height = 14, filename = file.path(figs_dir, str_glue("{metri}_TCR_patients_all_heatmap.pdf")))
}  
  

```



```{r}
objects_for_saving <- c( "annotations",  "corrtypes", 
"dend_", "dt_tcr_raw_w", "dt_tcr_raw_w_m", "figs_dir", "filter_corr_and_dend", 
"gtex_filt", "hclust.ave", "hclust.complete", "hclust.single", 
"i", "jsd_individuals_dist_list", "jsd_tcr_agg_individuals", 
"jsd_tcr_pairs", "metadata", "metri", "p_tcr_all", "pc_gene_list", 
"pmat_tcr_all", "samples_ordered", "samples_ordered_clean", "spear_individuals_dist_list", 
"spear_tcr_agg_individuals", "specific_tissue_key", "tcr_agg_individuals", 
"tcr_corrs", "tcr_raw", "tcr_raw_w", "tcr_raw_w_jsd", 
 "thesecolors", "tick_pos", "ticks", "tissue_key", 
"tmp", "tmpheight", "ugly_specific_tissue_key")
for(ob in objects_for_saving){
  if (!ob %in% ls()){
    print(paste0("Warning: ", ob, " not in environment"))
  }
  objects_for_saving <- objects_for_saving[objects_for_saving != ob]
}
save(list = objects_for_saving, file = "gtex_objects.RData")
```
 
 
 

```{r}

for (metri in c("jsd", "spearman")){
  tick_pos <- seq(0, 1, .1)
  if (metri == "jsd"){
    this_ob <- jsd_agg_dist_corr
    tmpheight <- sort(stats::cophenetic(this_ob[[1]]), decreasing = TRUE)[1] 
    ticks=data.frame(xorig=tick_pos, x=tick_pos - (1-tmpheight),
                     lab=rev(tick_pos),  yend=rep(.2, length(tick_pos)))  
    ticks <- ticks %>% filter(xorig >= min(1-this_ob[[2]]))
  } else {
    this_ob <- spear_agg_dist_corr
    tmpheight <- sort(stats::cophenetic(this_ob[[1]]), decreasing = TRUE)[1] 
    ticks=data.frame(xorig=tick_pos, x=tick_pos - (1-tmpheight),
                     lab=rev(tick_pos),  yend=rep(.2, length(tick_pos)))  
    ticks <- ticks %>% filter(xorig >= min(this_ob[[2]]))
  }
  tmp <- ape::as.phylo(this_ob[[1]])
  tmp$edge.length <- tmp$edge.length*2
  # need to do this in cases lacking single root
  
  
  tmp_anno <- data.frame(sample_name=rownames(this_ob[[2]])) %>% 
    mutate(
      patient = gsub("(.*?) - .*", "\\1", sample_name),
      tiss = gsub("(.*?) - (.*)", "\\2", sample_name),
    )
  # see  https://stackoverflow.com/questions/58492013/possible-to-force-non-occurring-elements-to-show-in-ggplot-legend
  # for why we use "limits" not "breaks" in the manual color scale
  (p <- ggtree(tmp)  %<+% tmp_anno  + xlim(min(ticks$x), max(ticks$x)*3) + 
      geom_tiplab(offset = 0.05,#(1-max(tmp$edge.length)) + .01, 
                  align = T, linetype = NA, size=3, 
      ) +
      geom_tippoint(position =position_nudge(x = 0.025), aes(color=patient, shape=tiss), size=3) +
      labs(title="GTEx",
           subtitle=str_glue("7 patients, distances based on {metri}")) + 
      scale_linetype(guide="none") + 
      scale_shape_manual(values=1:13)+
      scale_color_brewer(palette = "Paired") + 
      geom_segment(y=0, yend=0, x=min(ticks$x), xend=max(ticks$x)) + 
  #    geom_vline(xintercept = max(tmp$edge.length)) +
      theme(legend.position = c(.2, .6))+
      annotate(geom="text",        x=ticks$x, y=-.5, label=ticks$lab )   + 
      geom_segment(data=ticks, aes(y=-yend, yend=0, x=x, xend=x )) 
  )
  
  
  ggsave(
    p,
    width=8, height=18, file=str_glue("GTEx_samples_alltogether_{metri}.pdf")
  )
}
```

